name: 'Parallel ctest'
description: 'Runs a set of labeled ctests in parallel via multiple docker containers'
inputs:
  container:
    required: true
  error-log-paths:
    required: true
  log-tarball-prefix:
    required: true
  tests-label:
    required: true
  test-timeout:
    required: true
  batch-size:
    description: 'Number of tests to run concurrently (default: 10)'
    required: false
    default: '10'
runs:
  using: 'node20'
  main: 'dist/index.js'
