import { protoNameToRust } from "../util/names.js"
import { log } from "../util/logger.js"
import {
  FieldInfo,
  genStructMember,
  genFieldEncode,
  genFieldDecode
} from "./field.js"
import { PROTO_TYPE_MAP, WireType } from "./type-map.js"
import { genEnum } from "./enum.js"
import type { EnumDescriptor } from "./enum.js"

/**
 * Descriptor subset for a protobuf message needed by the codegen.
 */
export interface MessageDescriptor {
  /** Simple name (e.g. "MyMessage") */
  name: string
  /** Fully qualified name (e.g. ".my_package.MyMessage") */
  fullName: string
  /** Field descriptors */
  fields: FieldInfo[]
  /** Nested message descriptors (for map entry types, etc.) */
  nestedMessages: MessageDescriptor[]
  /** True if this message is a synthetic map entry */
  isMapEntry: boolean
}

/**
 * Collect all cross-file message type references from a set of messages.
 * Returns the set of fully-qualified type names that are NOT defined in
 * the current file's message list.
 *
 * Protobuf field `typeName` values always carry a leading dot (e.g.
 * `.sysio.opp.attestations.OperatorAction.ActionType`). We normalise every
 * local FQN the same way so the Set lookup works correctly — without this,
 * nested enum types (whose `fullName` has no leading dot) would never match
 * and would be emitted as spurious cross-file imports.
 */
function collectExternalTypes(
  messages: MessageDescriptor[],
  enums: EnumDescriptor[],
  currentProtoPackage: string
): Set<string> {
  const dot = (fqn: string) => (fqn.startsWith(".") ? fqn : `.${fqn}`)

  const localNames = new Set([
    ...messages.map(m => dot(m.fullName)),
    ...enums.map(e => dot(e.fullName))
  ])
  // Also include nested (map entry) message names
  for (const m of messages) {
    for (const nm of m.nestedMessages) {
      localNames.add(dot(nm.fullName))
    }
  }

  const external = new Set<string>()
  for (const msg of messages) {
    for (const field of msg.fields) {
      if ((field.type === 11 || field.type === 14) && field.typeName) {
        const fqn = dot(field.typeName)
        if (!localNames.has(fqn)) {
          external.add(fqn)
        }
      }
    }
  }
  return external
}

/**
 * Convert a fully-qualified proto type name to a Rust `use` path.
 * e.g. ".sysio.opp.types.ChainAddress" → "crate::sysio::opp::types::types::ChainAddress"
 *
 * The module path maps proto package segments to directory/file structure.
 * The last segment before the type name is repeated as the filename module.
 */
function fqnToRustUsePath(fqn: string): string {
  // Strip leading dot
  const parts = fqn.replace(/^\./, "").split(".")
  if (parts.length < 2) return ""
  // Last part is the type name, everything before is package path
  const typeName = parts[parts.length - 1]
  const packageParts = parts.slice(0, -1)
  // The module file name matches the last package segment (e.g. "types" → types.rs)
  const modulePath = packageParts.join("::")
  return `crate::${modulePath}::${packageParts[packageParts.length - 1]}::${typeName}`
}

/**
 * Generate `use` import lines for external types referenced by messages.
 */
function genExternalImports(
  messages: MessageDescriptor[],
  enums: EnumDescriptor[],
  currentProtoPackage: string
): string[] {
  const external = collectExternalTypes(messages, enums, currentProtoPackage)
  if (external.size === 0) return []

  // Build the current file's module path so we can exclude self-imports
  const currentModulePath = currentProtoPackage
    ? `crate::${currentProtoPackage.split(".").join("::")}::${currentProtoPackage.split(".").pop()}`
    : ""

  // Group by module path for wildcard imports
  const modules = new Map<string, Set<string>>()
  for (const fqn of external) {
    const parts = fqn.replace(/^\./, "").split(".")
    if (parts.length < 2) continue
    const typeName = parts[parts.length - 1]
    const packageParts = parts.slice(0, -1)
    const modulePath = `crate::${packageParts.join("::")}::${packageParts[packageParts.length - 1]}`

    // Skip self-imports
    if (modulePath === currentModulePath) continue

    if (!modules.has(modulePath)) {
      modules.set(modulePath, new Set())
    }
    modules.get(modulePath)!.add(typeName)
  }

  const lines: string[] = []
  for (const [mod, _types] of modules) {
    lines.push(`use ${mod}::*;`)
  }
  return lines
}

/**
 * Generate a complete .rs file containing struct definitions and
 * encode/decode impl blocks for all non-map-entry messages
 * in a given proto file.
 */
export function generateRsFile(
  messages: MessageDescriptor[],
  protoFileName: string,
  protoPackage?: string,
  enums: EnumDescriptor[] = []
): string {
  const lines: string[] = []

  lines.push(`// Auto-generated by protoc-gen-solana from ${protoFileName}`)
  lines.push(`// DO NOT EDIT`)
  lines.push(``)
  lines.push(`#![allow(unused_imports, non_camel_case_types, dead_code)]`)
  lines.push(``)
  lines.push(`use crate::protobuf_runtime::*;`)

  // Add cross-module imports for types from other proto files
  const externalImports = genExternalImports(messages, enums, protoPackage || "")
  for (const imp of externalImports) {
    lines.push(imp)
  }

  lines.push(``)

  // Generate enum definitions first (structs may reference them)
  for (const enumDesc of enums) {
    lines.push(genEnum(enumDesc))
    lines.push(``)
  }

  // Generate structs with encode/decode impls
  for (const msg of messages) {
    if (msg.isMapEntry) continue
    lines.push(genStruct(msg))
    lines.push(``)
    lines.push(genImpl(msg))
    lines.push(``)
  }

  return lines.join("\n")
}

/**
 * Generate Rust struct definition for a message.
 */
function genStruct(msg: MessageDescriptor): string {
  const name = protoNameToRust(msg.fullName)
  log.debug(`Generating struct ${name} (${msg.fields.length} fields)`)

  const members = msg.fields
    .filter(f => !isMapEntryField(f, msg))
    .map(f => {
      const mapEntry = resolveMapEntry(f, msg)
      if (mapEntry) {
        return genStructMember({ ...f, mapEntry })
      }
      return genStructMember(f)
    })

  return [
    `#[derive(Clone, Debug, Default, PartialEq)]`,
    `#[cfg_attr(feature = "borsh", derive(borsh::BorshSerialize, borsh::BorshDeserialize))]`,
    `pub struct ${name} {`,
    ...members,
    `}`
  ].join("\n")
}

/**
 * Generate the impl block with encode() and decode() for a message.
 */
function genImpl(msg: MessageDescriptor): string {
  const structName = protoNameToRust(msg.fullName)

  log.debug(`Generating impl ${structName}`)

  const encodeBody = genEncodeFunction(msg, structName)
  const decodeBody = genDecodeFunction(msg, structName)

  return [
    `impl ${structName} {`,
    ``,
    encodeBody,
    ``,
    decodeBody,
    `}`
  ].join("\n")
}

/**
 * Generate the encode function body.
 */
function genEncodeFunction(
  msg: MessageDescriptor,
  structName: string
): string {
  const lines: string[] = []
  lines.push(`    pub fn encode(&self) -> Vec<u8> {`)
  lines.push(`        let mut buf = Vec::new();`)

  for (const field of msg.fields) {
    if (isMapEntryField(field, msg)) continue

    const mapEntry = resolveMapEntry(field, msg)
    const fieldInfo = mapEntry ? { ...field, mapEntry } : field

    lines.push(``)
    lines.push(`        // field ${field.number}: ${field.name}`)
    lines.push(genFieldEncode(fieldInfo))
  }

  lines.push(``)
  lines.push(`        buf`)
  lines.push(`    }`)
  return lines.join("\n")
}

/**
 * Generate the decode function body with tag-dispatch loop.
 */
function genDecodeFunction(
  msg: MessageDescriptor,
  structName: string
): string {
  const lines: string[] = []
  lines.push(
    `    pub fn decode(data: &[u8]) -> Result<Self, DecodeError> {`
  )
  lines.push(`        let mut msg = Self::default();`)
  lines.push(`        let mut pos = 0usize;`)
  lines.push(`        let end = data.len();`)
  lines.push(``)
  lines.push(`        while pos < end {`)
  lines.push(`            let (tag, new_pos) = decode_key(data, pos)?;`)
  lines.push(`            pos = new_pos;`)
  lines.push(``)
  lines.push(`            match tag {`)

  for (const field of msg.fields) {
    if (isMapEntryField(field, msg)) continue

    const mapEntry = resolveMapEntry(field, msg)
    const fieldInfo = mapEntry ? { ...field, mapEntry } : field

    lines.push(genFieldDecode(fieldInfo))
  }

  lines.push(`            _ => {`)
  lines.push(`                pos = skip_field(data, pos, tag & 0x07)?;`)
  lines.push(`            }`)
  lines.push(`            }`)
  lines.push(`        }`)
  lines.push(``)
  lines.push(`        Ok(msg)`)
  lines.push(`    }`)
  return lines.join("\n")
}

// ── Map entry resolution ──────────────────────────────────────────────

interface MapEntryInfo {
  keyType: number
  valueType: number
  valueTypeName?: string
}

/**
 * Check if a field references a map entry message type.
 */
function isMapEntryField(
  field: FieldInfo,
  parentMsg: MessageDescriptor
): boolean {
  if (field.type !== 11 || field.label !== 3) return false
  const nested = parentMsg.nestedMessages.find(
    m => field.typeName?.endsWith(`.${m.name}`)
  )
  return nested?.isMapEntry ?? false
}

/**
 * Resolve a map entry's key/value types from the synthetic nested message.
 */
function resolveMapEntry(
  field: FieldInfo,
  parentMsg: MessageDescriptor
): MapEntryInfo | undefined {
  if (field.type !== 11 || field.label !== 3) return undefined
  const nested = parentMsg.nestedMessages.find(
    m => field.typeName?.endsWith(`.${m.name}`)
  )
  if (!nested?.isMapEntry) return undefined

  const keyField = nested.fields.find(f => f.number === 1)
  const valField = nested.fields.find(f => f.number === 2)
  if (!keyField || !valField) return undefined

  return {
    keyType: keyField.type,
    valueType: valField.type,
    valueTypeName: valField.typeName
  }
}
