#!/usr/bin/env python3

import time
import json
import os
import shutil
import signal

from TestHarness import Account, Cluster, TestHelper, Utils, WalletMgr
from TestHarness.TestHelper import AppArgs

###############################################################
# ship_streamer_test
# 
# This test sets up 4 producing nodes and one "bridge" node using test_control_api_plugin.
#   One side of bridge has 3 of the elected producers and the other has 1 of the elected producers.
#   All the producers are named in alphabetical order, so that the 3 producers, in the one production side, are
#       scheduled first, followed by the 1 producer in the other producer node. Each producing side is only connected
#       to the other producing node via the "bridge" node.
#   The bridge node has the test_control_api_plugin, that the test uses to kill
#       the "bridge" node to generate a fork.
#   ship_streamer is used to connect to the state_history_plugin and verify that blocks receive link to previous
#   blocks. If the blocks do not link then ship_streamer will exit with an error causing this test to generate an
#   error. The fork generated by nodeop should be sent to the ship_streamer so it is able to correctly observe the
#   fork.
#
###############################################################

Print=Utils.Print

appArgs = AppArgs()
extraArgs = appArgs.add(flag="--num-clients", type=int, help="How many ship_streamers should be started", default=1)
extraArgs = appArgs.add_bool(flag="--finality-data-history", help="Enable finality data history", action='store_true')
args = TestHelper.parse_args({"--activate-if","--dump-error-details","--keep-logs","-v","--leave-running","--unshared"}, applicationSpecificArgs=appArgs)

Utils.Debug=args.v
cluster=Cluster(unshared=args.unshared, keepRunning=args.leave_running, keepLogs=args.keep_logs)
activateIF=args.activate_if
dumpErrorDetails=args.dump_error_details
walletPort=TestHelper.DEFAULT_WALLET_PORT

totalProducerNodes=4
totalNonProducerNodes=1
totalNodes=totalProducerNodes+totalNonProducerNodes
maxActiveProducers=21
totalProducers=maxActiveProducers

walletMgr=WalletMgr(True, port=walletPort)
testSuccessful=False

WalletdName=Utils.SysWalletName
shipTempDir=None
shipClientMaxRetries=2
transientShipClientErrors=(
    "End of file",
    "No buffer space available",
    "Connection reset",
    "Connection refused",
)

try:
    TestHelper.printSystemInfo("BEGIN")

    cluster.setWalletMgr(walletMgr)
    Print("Stand up cluster")

    # ***   setup topogrophy   ***

    # "bridge" shape connects defproducera (node0) defproducerb (node1) defproducerc (node2) to each other and defproducerd (node3)
    # and the only connection between those 2 groups is through the bridge (node4)

    shipNodeNum = 3
    specificExtraNodeopArgs={}
    specificExtraNodeopArgs[shipNodeNum]=(
        "--plugin sysio::state_history_plugin "
        "--trace-history --chain-state-history "
        "--state-history-stride 200 "
        f"--state-history-endpoint 127.0.0.1:{Utils.getPort(Utils.PortStateHistory)} "
        "--plugin sysio::net_api_plugin --plugin sysio::producer_api_plugin "
    )
    if args.finality_data_history:
        specificExtraNodeopArgs[shipNodeNum]+=" --finality-data-history"
    # producer nodes will be mapped to 0 through totalProducerNodes-1, so the number totalProducerNodes will be the non-producing node
    specificExtraNodeopArgs[totalProducerNodes]="--plugin sysio::test_control_api_plugin  "
    # test wants to generate a long fork
    extraNodeopArgs=" --production-pause-vote-timeout-ms 0 "

    if cluster.launch(topo="./tests/bridge_for_fork_test_shape.json", pnodes=totalProducerNodes, loadSystemContract=False,
                      totalNodes=totalNodes, totalProducers=totalProducerNodes, activateIF=activateIF, biosFinalizer=False,
                      extraNodeopArgs=extraNodeopArgs, specificExtraNodeopArgs=specificExtraNodeopArgs) is False:
        Utils.cmdError("launcher")
        Utils.errorExit("Failed to stand up cluster.")

    # ***   identify each node (producers and non-producing node)   ***

    # verify nodes are in sync and advancing
    cluster.waitOnClusterSync(blockAdvancing=5)
    Print("Cluster in Sync")

    prodNode0 = cluster.getNode(0)
    prodNode3 = cluster.getNode(3)
    nonProdNode = cluster.getNode(4)
    shipNode = cluster.getNode(shipNodeNum)

    start_block_num = shipNode.getBlockNum()

    #verify nodes are in sync and advancing
    cluster.waitOnClusterSync(blockAdvancing=3)
    Print("Shutdown unneeded bios node")
    cluster.biosNode.kill(signal.SIGTERM)

    Print("Create a jumbo row")
    jumboAcc = Account("itsjumbotime")
    jumboAcc.ownerPublicKey = "SYS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
    jumboAcc.activePublicKey = "SYS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
    nonProdNode.createInitializeAccount(jumboAcc, cluster.sysioAccount, nodeOwner=cluster.carlAccount, stakedDeposit=0, waitForTransBlock=False, stakeNet=10000, stakeCPU=10000, buyRAM=2000000, exitOnError=True)

    contract = "jumborow"
    contractDir = "unittests/system-test-contracts/%s" % (contract)
    wasmFile = "%s.wasm" % (contract)
    abiFile = "%s.abi" % (contract)

    trans = nonProdNode.publishContract(jumboAcc, contractDir, wasmFile, abiFile)
    if trans is None:
        Utils.errorExit("ERROR: Failed to publish contract %s." % (contract))

    jumbotxn = {
        "actions": [{"account": "itsjumbotime","name": "jumbotime",
                     "authorization": [{"actor": "itsjumbotime","permission": "active"}],
                     "data": "",
                     "compression": "none"}]
    }
    results = nonProdNode.pushTransaction(jumbotxn)
    assert(results[0])

    Print("Configure and launch txn generators")
    targetTpsPerGenerator = 10
    testTrxGenDurationSec=60*60
    numTrxGenerators=2
    cluster.launchTrxGenerators(contractOwnerAcctName=cluster.sysioAccount.name, acctNamesList=[cluster.defproduceraAccount.name, cluster.defproducerbAccount.name],
                                acctPrivKeysList=[cluster.defproduceraAccount.activePrivateKey,cluster.defproducerbAccount.activePrivateKey], nodeId=prodNode3.nodeId,
                                tpsPerGenerator=targetTpsPerGenerator, numGenerators=numTrxGenerators, durationSec=testTrxGenDurationSec,
                                waitToComplete=False)

    status = cluster.waitForTrxGeneratorsSpinup(nodeId=prodNode3.nodeId, numGenerators=numTrxGenerators)
    assert status is not None and status is not False, "ERROR: Failed to spinup Transaction Generators"

    prodNode0.waitForProducer("defproducerc")

    block_range = 250
    end_block_num = start_block_num + block_range

    shipClient = "tests/ship_streamer"
    shipSocketAddress = f"127.0.0.1:{Utils.getPort(Utils.PortStateHistory)}"

    def makeShipStreamerCmd(startBlockNum, endBlockNum):
        """Return a ship_streamer command targeting this test's sharded SHiP endpoint."""
        return (
            f"{shipClient} --socket-address {shipSocketAddress} "
            f"--start-block-num {startBlockNum} --end-block-num {endBlockNum} "
            "--fetch-block --fetch-traces --fetch-deltas"
        )

    cmd = makeShipStreamerCmd(start_block_num, end_block_num)
    if args.finality_data_history:
        cmd += "  --fetch-finality-data"
    if Utils.Debug: Utils.Print(f"cmd: {cmd}")
    shipTempDir = os.path.join(Utils.DataDir, "ship")
    os.makedirs(shipTempDir, exist_ok = True)
    shipClientFilePrefix = os.path.join(shipTempDir, "client")

    def isTransientShipClientError(stderr):
        """Return true when a ship_streamer failure is safe to retry."""
        return any(error in stderr for error in transientShipClientErrors)

    def shipClientLogPath(index, phase, attempt, extension):
        """Return the stdout or stderr path for one ship_streamer client attempt."""
        retrySuffix = "" if attempt == 0 else f"_retry{attempt}"
        return f"{shipClientFilePrefix}{index}{phase}{retrySuffix}.{extension}"

    def readTextFile(path):
        """Read a text log file, returning an empty string when the file is absent."""
        if not os.path.exists(path):
            return ""
        with open(path, "r") as logFile:
            return logFile.read()

    def startShipClient(index, cmd, phase="", attempt=0):
        """Start one ship_streamer client and return its process and log handles."""
        outPath = shipClientLogPath(index, phase, attempt, "out")
        errPath = shipClientLogPath(index, phase, attempt, "err")
        outFile = open(outPath, "w")
        errFile = open(errPath, "w")
        Print(f"Start client {index}" if attempt == 0 else f"Retry client {index}, attempt {attempt}")
        start = time.perf_counter()
        popen = Utils.delayedCheckOutput(cmd, stdout=outFile, stderr=errFile)
        Print(f"Client {index} started, Ship node head is: {shipNode.getBlockNum()}")
        return (popen, outFile, errFile, start, outPath, errPath)

    def waitForShipClient(index, popen, outFile, errFile, start, errPath):
        """Wait for one ship_streamer client and return its exit code and stderr."""
        returnCode = popen.wait()
        Print(f"Stopped client {index}.  Ran for {time.perf_counter() - start:.3f} seconds.")
        outFile.close()
        errFile.close()
        stderr = readTextFile(errPath)
        return (returnCode, stderr)

    def parseShipClientOutput(index, outPath, errPath):
        """Load one ship_streamer JSON result, including log paths in failures."""
        try:
            with open(outPath, "r") as outFile:
                return json.load(outFile)
        except json.JSONDecodeError as ex:
            stderr = readTextFile(errPath)
            Utils.errorExit(
                f"Client {index} produced invalid JSON in {outPath}: {ex}. "
                f"stderr from {errPath}: {stderr}"
            )
            raise

    def validateShipClientData(index, data, startBlockNum, endBlockNum, expectedField):
        """Verify streamed SHiP results are contiguous and include the expected payload field."""
        block_num = startBlockNum
        for i in data:
            # fork can cause block numbers to be repeated
            this_block_num = i['get_blocks_result_v1']['this_block']['block_num']
            if this_block_num < block_num:
                block_num = this_block_num
            assert block_num == this_block_num, f"client {index}: {block_num} != {this_block_num}"
            assert isinstance(i['get_blocks_result_v1'][expectedField], str)
            block_num += 1
        assert block_num-1 == endBlockNum, f"client {index}: {block_num-1} != {endBlockNum}"

    def retryShipClient(index, cmd, phase, startBlockNum, endBlockNum, expectedField):
        """Retry one failed ship_streamer client when the failure is transient."""
        stderr = ""
        for attempt in range(1, shipClientMaxRetries + 1):
            popen, outFile, errFile, start, outPath, errPath = startShipClient(index, cmd, phase, attempt)
            returnCode, stderr = waitForShipClient(index, popen, outFile, errFile, start, errPath)
            if returnCode == 0:
                data = parseShipClientOutput(index, outPath, errPath)
                validateShipClientData(index, data, startBlockNum, endBlockNum, expectedField)
                return
            if not isTransientShipClientError(stderr):
                Utils.errorExit(f"Client {index} retry {attempt} failed with return code {returnCode}: {stderr}")
            if attempt < shipClientMaxRetries:
                Print(f"Client {index} retry {attempt} hit a transient SHiP error, retrying again")
                time.sleep(attempt)
        Utils.errorExit(f"Client {index} failed after {shipClientMaxRetries} retries: {stderr}")

    def runShipClients(cmd, phase, startBlockNum, endBlockNum, expectedField):
        """Run all ship_streamer clients concurrently, retrying transient per-client failures."""
        clients = []
        for i in range(0, args.num_clients):
            clients.append((i, *startShipClient(i, cmd, phase)))

        Print(f"Waiting for all {args.num_clients} clients")
        for index, popen, outFile, errFile, start, outPath, errPath in clients:
            returnCode, stderr = waitForShipClient(index, popen, outFile, errFile, start, errPath)
            if returnCode == 0:
                data = parseShipClientOutput(index, outPath, errPath)
                validateShipClientData(index, data, startBlockNum, endBlockNum, expectedField)
                continue
            if isTransientShipClientError(stderr):
                Print(f"Client {index} failed with transient SHiP error, retrying: {stderr}")
                retryShipClient(index, cmd, phase, startBlockNum, endBlockNum, expectedField)
                continue
            Utils.errorExit(f"Client {index} failed with return code {returnCode}: {stderr}")

    clients = []
    for i in range(0, args.num_clients):
        clients.append((i, *startShipClient(i, cmd)))

    # Generate a fork
    nonProdNode.waitForProducer("defproducera")
    prodNode3Prod= "defproducerd"
    preKillBlockNum=nonProdNode.getBlockNum()
    preKillBlockProducer=nonProdNode.getBlockProducerByNum(preKillBlockNum)
    forkAtProducer="defproducerb"
    nonProdNode.killNodeOnProducer(producer=forkAtProducer, whereInSequence=1)
    Print(f"Current block producer {preKillBlockProducer} fork will be at producer {forkAtProducer}")
    prodNode0.waitForProducer("defproducerc")
    prodNode3.waitForProducer(prodNode3Prod)
    if nonProdNode.verifyAlive():
        Utils.errorExit("Bridge did not shutdown")
    Print("Fork started")

    prodNode0.waitForProducer("defproducerc") # wait for fork to progress a bit
    restore0BlockNum = prodNode0.getBlockNum()
    restore1BlockNum = prodNode3.getBlockNum()
    restoreBlockNum = max(int(restore0BlockNum), int(restore1BlockNum))
    restore0LIB = prodNode0.getIrreversibleBlockNum()
    restore1LIB = prodNode3.getIrreversibleBlockNum()
    restoreLIB = max(int(restore0LIB), int(restore1LIB))

    if int(restoreBlockNum) > int(end_block_num):
        Utils.errorExit(f"Did not stream long enough {end_block_num} to cover the fork {restoreBlockNum}, increase block_range {block_range}")

    Print("Restore fork")
    Print("Relaunching the non-producing bridge node to connect the producing nodes again")
    if nonProdNode.verifyAlive():
        Utils.errorExit("Bridge is already running")
    if not nonProdNode.relaunch():
        Utils.errorExit(f"Failure - (non-production) node {nonProdNode.nodeNum} should have restarted")

    nonProdNode.waitForProducer(forkAtProducer)
    nonProdNode.waitForProducer(prodNode3Prod)
    nonProdNode.waitForIrreversibleBlock(restoreLIB+1)

    assert shipNode.findInLog(f"successfully switched fork to new head"), f"No fork found in log {shipNode}"

    Print(f"Waiting for all {args.num_clients} clients")
    for index, popen, outFile, errFile, start, outPath, errPath in clients:
        returnCode, stderr = waitForShipClient(index, popen, outFile, errFile, start, errPath)
        if returnCode == 0:
            data = parseShipClientOutput(index, outPath, errPath)
            validateShipClientData(index, data, start_block_num, end_block_num, "block")
            continue
        if isTransientShipClientError(stderr):
            Print(f"Client {index} failed with transient SHiP error, retrying: {stderr}")
            retryShipClient(index, cmd, "", start_block_num, end_block_num, "block")
            continue
        Utils.errorExit(f"Client {index} failed with return code {returnCode}: {stderr}")

    Print("Generate snapshot")
    shipNode.createSnapshot()

    Print("Shutdown state_history_plugin nodeop")
    shipNode.kill(signal.SIGTERM)

    Print("Shutdown bridge node")
    nonProdNode.kill(signal.SIGTERM)

    Print("Test starting ship from replay")
    isRelaunchSuccess = shipNode.relaunch(chainArg=" --replay-blockchain")
    assert isRelaunchSuccess, "relaunch from replay failed"

    afterReplayBlockNum = shipNode.getBlockNum()

    Print("Verify we can stream from ship after start from a replay with no incoming trxs")
    start_block_num = afterReplayBlockNum
    block_range = 0
    end_block_num = start_block_num + block_range
    cmd = makeShipStreamerCmd(start_block_num, end_block_num)
    if args.finality_data_history:
        cmd += "  --fetch-finality-data"
    if Utils.Debug: Utils.Print(f"cmd: {cmd}")
    runShipClients(cmd, "_replay", start_block_num, end_block_num, "deltas")

    Print("Shutdown state_history_plugin nodeop after replay")
    shipNode.kill(signal.SIGTERM)

    Print("Test starting ship from snapshot")
    shipNode.removeDataDir()
    isRelaunchSuccess = shipNode.relaunch(rmArgs="--replay-blockchain", chainArg=" --snapshot {}".format(shipNode.getLatestSnapshot()))
    assert isRelaunchSuccess, "relaunch from snapshot failed"

    afterSnapshotBlockNum = shipNode.getBlockNum()

    Print("Verify we can stream from ship after start from a snapshot with no incoming trxs")
    start_block_num = afterSnapshotBlockNum
    block_range = 0
    end_block_num = start_block_num + block_range
    cmd = makeShipStreamerCmd(start_block_num, end_block_num)
    if args.finality_data_history:
        cmd += "  --fetch-finality-data"
    if Utils.Debug: Utils.Print(f"cmd: {cmd}")
    runShipClients(cmd, "_snapshot", start_block_num, end_block_num, "deltas")

    testSuccessful = True
finally:
    TestHelper.shutdown(cluster, walletMgr, testSuccessful=testSuccessful, dumpErrorDetails=dumpErrorDetails)
    if shipTempDir is not None:
        if testSuccessful and not args.keep_logs:
            shutil.rmtree(shipTempDir, ignore_errors=True)

errorCode = 0 if testSuccessful else 1
exit(errorCode)
