#pragma once

#include <cstdint>

namespace sysio::protocol::snapshot_attestation {

/// Fixed distance between snapshot heights accepted by the contract and generated by providers.
inline constexpr uint32_t block_spacing = 25000;

/** Return whether a block height belongs to the fixed snapshot attestation cadence. */
constexpr bool is_scheduled_block(uint32_t block_num) {
   return block_num > 0 && block_num % block_spacing == 0;
}

/// Contract error code emitted when a provider's local tuple conflicts with a final record.
inline constexpr uint64_t disagreement_error_code = 9001;

/// Name of the provider vote action.
inline constexpr auto action_votesnaphash = "votesnaphash";

/// Name of the provider-registration action.
inline constexpr auto action_regsnapprov = "regsnapprov";

/// Name of the snapshot-attestation configuration action.
inline constexpr auto action_setsnapcfg = "setsnpcfg";

/// Name of the final snapshot-attestation record table.
inline constexpr auto table_snaprecords = "snaprecords";

/// ABI struct stored by the final snapshot-attestation record table.
inline constexpr auto type_snap_record = "snap_record";

/// ABI primary-index kind required by the block-number keyed record table.
inline constexpr auto index_type_i64 = "i64";

/// ABI primitive type identifiers used by the final record schema.
namespace abi_type {

/// ABI spelling for a 32-byte checksum.
inline constexpr auto checksum256 = "checksum256";

/// ABI spelling for a 32-bit unsigned integer.
inline constexpr auto uint32 = "uint32";

/// ABI spelling for a 64-bit unsigned integer.
inline constexpr auto uint64 = "uint64";

} // namespace abi_type

/// ABI field identifiers used by host-side table readers.
namespace field {

/// Minimum registered-provider count required before voting can begin.
inline constexpr auto min_providers = "min_providers";

/// Producer account associated with a snapshot provider.
inline constexpr auto producer = "producer";

/// Snapshot-provider account authorized to submit a vote.
inline constexpr auto snap_account = "snap_account";

/// Chain block that included the final attestation record.
inline constexpr auto attested_at_block = "attested_at_block";

/// Final tuple block identifier.
inline constexpr auto block_id = "block_id";

/// Final tuple block height.
inline constexpr auto block_num = "block_num";

/// Final snapshot root hash.
inline constexpr auto snapshot_hash = "snapshot_hash";

/// Percentage of registered providers required to finalize a tuple.
inline constexpr auto threshold_pct = "threshold_pct";

} // namespace field

} // namespace sysio::protocol::snapshot_attestation
