#!/usr/bin/env bash

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$ROOT_DIR/build}"
EFFECTIVE_BUILD_DIR=""
JOBS="${JOBS:-$(nproc)}"
RUN_TESTS=0
CLEAN="${WIRE_SYSIO_CLEAN_BUILD:-}"
NEEDS_CI_OWNERSHIP_FIX=0
BUILD_MODE="${WIRE_SYSIO_BUILD_MODE:-developer}"
BUILD_MODE_EXPLICIT=0
CMAKE_PRESET="${WIRE_SYSIO_CMAKE_PRESET:-}"
CMAKE_PRESET_EXPLICIT=0
VCPKG_NUGET_FEED="${VCPKG_NUGET_FEED:-https://nuget.pkg.github.com/Wire-Network/index.json}"

if [[ -n "${WIRE_SYSIO_BUILD_MODE:-}" ]]; then
  BUILD_MODE_EXPLICIT=1
fi

if [[ -n "$CMAKE_PRESET" ]]; then
  CMAKE_PRESET_EXPLICIT=1
fi

usage() {
  cat <<USAGE
Usage: $0 [options]

Build Wire Sysio with the GitHub Packages vcpkg NuGet binary cache.

Options:
  --build-dir DIR       Developer mode build directory prefix; dev-release
                       uses DIR/release and dev-debug uses
                       DIR/debug-release-deps. CI modes use DIR as the exact
                       CMake build directory. Default: $BUILD_DIR
  --preset NAME         CMake configure/build preset. Defaults by mode:
                       developer=dev-release,
                       trusted-ci=vcpkg-github-release-ci,
                       forked-pr-ci=vcpkg-local-release-fork.
  --jobs N             Parallel build jobs. Default: $JOBS
  --clean              Remove vcpkg build artifacts before configuring.
                       Default: enabled in CI modes, disabled in developer mode.
  --run-tests          Run the parallel-safe test subset after building.
  --mode MODE          Build mode: developer, trusted-ci, or forked-pr-ci.
                       Default: inferred from known --preset values, otherwise
                       $BUILD_MODE.
  -h, --help           Show this help.

Environment:
  VCPKG_NUGET_FEED     NuGet feed URL. Default: $VCPKG_NUGET_FEED
  GITHUB_TOKEN         GitHub token. Required for trusted-ci mode.
  GITHUB_USER          GitHub username or owner. Required for trusted-ci mode.
  WIRE_SYSIO_CMAKE_PRESET
                       CMake preset to use when --preset is not passed.
  CMakeUserPresets.json
                       Developer mode writes IDE-friendly local presets here
                       when the file is absent or was generated by this script.
  CC, CXX              Optional C and C++ compiler overrides.
  CMAKE_PREFIX_PATH    Optional CMake package prefix path.
USAGE
}

fail() {
  local message="$1"
  local correction="$2"

  printf '\nERROR: %s\n\nCorrection:\n%b\n\n' "$message" "$correction" >&2
  exit 1
}

info() {
  printf '==> %s\n' "$*"
}

require_command() {
  local command_name="$1"
  local package_hint="$2"

  if ! command -v "$command_name" >/dev/null 2>&1; then
    fail "'$command_name' is not installed." "Install it with:\n  sudo apt-get install -y $package_hint"
  fi
}

require_positive_integer() {
  local value="$1"
  local name="$2"

  if [[ ! "$value" =~ ^[1-9][0-9]*$ ]]; then
    fail "$name must be a positive integer." "Use '$0 --jobs $(nproc)' or set JOBS to a positive integer."
  fi
}

preset_mode() {
  local preset="$1"

  case "$preset" in
    dev-release|dev-debug|vcpkg-github-release|vcpkg-github-debug-release-deps)
      printf 'developer'
      ;;
    vcpkg-github-release-ci)
      printf 'trusted-ci'
      ;;
    vcpkg-local-release-fork)
      printf 'forked-pr-ci'
      ;;
  esac
}

developer_binary_dir() {
  local suffix="$1"
  local absolute_dir
  local relative_dir

  absolute_dir="$(realpath -m "$BUILD_DIR/$suffix")"
  relative_dir="$(realpath -m --relative-to="$ROOT_DIR" "$absolute_dir")"

  if [[ "$relative_dir" != .. && "$relative_dir" != ../* ]]; then
    printf '${sourceDir}/%s' "$relative_dir"
  else
    printf '%s' "$absolute_dir"
  fi
}

write_developer_user_presets() {
  local file="$ROOT_DIR/CMakeUserPresets.json"
  local marker='"wire-sysio/generated-by": "scripts/build-with-github-vcpkg-cache.sh"'
  local binary_sources_json
  local debug_build_dir_json
  local disable_metrics_json
  local release_build_dir_json

  if [[ -f "$file" ]] && ! grep -q "$marker" "$file"; then
    info "Leaving existing CMakeUserPresets.json unchanged because it was not generated by this script"
    return 1
  fi

  binary_sources_json="$(printf '%s' "$VCPKG_BINARY_SOURCES" | jq -Rs .)"
  release_build_dir_json="$(developer_binary_dir "release" | jq -Rs .)"
  debug_build_dir_json="$(developer_binary_dir "debug-release-deps" | jq -Rs .)"
  disable_metrics_json="$(printf '%s' "$VCPKG_DISABLE_METRICS" | jq -Rs .)"

  cat > "$file" <<PRESETS
{
  "version": 6,
  "vendor": {
    "wire-sysio/generated-by": "scripts/build-with-github-vcpkg-cache.sh"
  },
  "configurePresets": [
    {
      "name": "dev-release",
      "displayName": "Developer release with GitHub vcpkg cache",
      "inherits": "vcpkg-github-release",
      "binaryDir": $release_build_dir_json,
      "environment": {
        "VCPKG_BINARY_SOURCES": $binary_sources_json,
        "VCPKG_DISABLE_METRICS": $disable_metrics_json
      }
    },
    {
      "name": "dev-debug",
      "displayName": "Developer debug with GitHub vcpkg cache release deps",
      "inherits": "vcpkg-github-debug-release-deps",
      "binaryDir": $debug_build_dir_json,
      "environment": {
        "VCPKG_BINARY_SOURCES": $binary_sources_json,
        "VCPKG_DISABLE_METRICS": $disable_metrics_json
      }
    }
  ],
  "buildPresets": [
    {
      "name": "dev-release",
      "configurePreset": "dev-release"
    },
    {
      "name": "dev-debug",
      "configurePreset": "dev-debug"
    }
  ]
}
PRESETS

  info "Wrote CMakeUserPresets.json with developer vcpkg cache presets"
  return 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-dir)
      [[ $# -ge 2 ]] || fail "--build-dir requires a value." "Run '$0 --build-dir /path/to/build'."
      BUILD_DIR="$2"
      shift 2
      ;;
    --preset)
      [[ $# -ge 2 ]] || fail "--preset requires a value." "Run '$0 --preset vcpkg-github-release'."
      CMAKE_PRESET="$2"
      CMAKE_PRESET_EXPLICIT=1
      shift 2
      ;;
    --jobs)
      [[ $# -ge 2 ]] || fail "--jobs requires a value." "Run '$0 --jobs $(nproc)'."
      JOBS="$2"
      shift 2
      ;;
    --clean)
      CLEAN=1
      shift
      ;;
    --run-tests)
      RUN_TESTS=1
      shift
      ;;
    --mode)
      [[ $# -ge 2 ]] || fail "--mode requires a value." "Use '--mode developer', '--mode trusted-ci', or '--mode forked-pr-ci'."
      BUILD_MODE="$2"
      BUILD_MODE_EXPLICIT=1
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown option '$1'." "Run '$0 --help' to see supported options."
      ;;
  esac
done

if [[ "$CMAKE_PRESET_EXPLICIT" -eq 1 ]]; then
  PRESET_MODE="$(preset_mode "$CMAKE_PRESET")"
  if [[ -n "$PRESET_MODE" ]]; then
    if [[ "$BUILD_MODE_EXPLICIT" -eq 1 && "$BUILD_MODE" != "$PRESET_MODE" ]]; then
      fail "Preset '$CMAKE_PRESET' is only compatible with mode '$PRESET_MODE', but mode '$BUILD_MODE' was requested." "Use '--mode $PRESET_MODE --preset $CMAKE_PRESET', or choose a preset that matches '$BUILD_MODE'."
    fi
    if [[ "$BUILD_MODE_EXPLICIT" -eq 0 ]]; then
      BUILD_MODE="$PRESET_MODE"
    fi
  fi
fi

if [[ "$BUILD_MODE" != "developer" && "$BUILD_MODE" != "trusted-ci" && "$BUILD_MODE" != "forked-pr-ci" ]]; then
  fail "Unsupported build mode '$BUILD_MODE'." "Use '--mode developer' for local builds, '--mode trusted-ci' for trusted GitHub Actions runs, or '--mode forked-pr-ci' for fork pull requests."
fi

require_positive_integer "$JOBS" "--jobs"

if [[ -z "$CMAKE_PRESET" ]]; then
  case "$BUILD_MODE" in
    developer)
      CMAKE_PRESET="dev-release"
      ;;
    trusted-ci)
      CMAKE_PRESET="vcpkg-github-release-ci"
      ;;
    forked-pr-ci)
      CMAKE_PRESET="vcpkg-local-release-fork"
      ;;
  esac
fi

if [[ -z "$CLEAN" ]]; then
  if [[ "$BUILD_MODE" == "developer" ]]; then
    CLEAN=0
  else
    CLEAN=1
  fi
fi

if [[ "$BUILD_MODE" == "trusted-ci" || "$BUILD_MODE" == "forked-pr-ci" ]]; then
  NEEDS_CI_OWNERSHIP_FIX=1
fi

if [[ ! -f "$ROOT_DIR/CMakeLists.txt" || ! -d "$ROOT_DIR/vcpkg" ]]; then
  fail "The script could not locate the Wire Sysio repository root." "Run this script from a complete Wire Sysio checkout with submodules initialized:\n  git submodule update --init --recursive"
fi

require_command cmake cmake
require_command ninja ninja-build
require_command git git

if [[ "$BUILD_MODE" != "forked-pr-ci" ]]; then
  require_command mono mono-complete
fi

if [[ "$BUILD_MODE" == "developer" ]]; then
  require_command gh gh
  require_command jq jq
fi

if [[ "$NEEDS_CI_OWNERSHIP_FIX" -eq 1 ]]; then
  chown -R "$(id -u):$(id -g)" "$ROOT_DIR"
fi

if [[ "$CLEAN" == "1" ]]; then
  rm -rf "$ROOT_DIR/vcpkg/buildtrees" "$ROOT_DIR/vcpkg/packages" "$ROOT_DIR/vcpkg/vcpkg_installed" \
         "$BUILD_DIR/vcpkg_installed" ~/.cache/vcpkg ~/.vcpkg
fi

info "Bootstrapping vcpkg"
"$ROOT_DIR/vcpkg/bootstrap-vcpkg.sh"

export VCPKG_DISABLE_METRICS="${VCPKG_DISABLE_METRICS:-1}"

if [[ "$BUILD_MODE" == "forked-pr-ci" ]]; then
  # Fork PRs cannot use package credentials, so they intentionally fall back to
  # vcpkg's ephemeral runner-local binary cache and may rebuild dependencies.
  export VCPKG_BINARY_SOURCES="clear;default,readwrite"
else
  if [[ "$BUILD_MODE" == "trusted-ci" ]]; then
    GITHUB_TOKEN="${GITHUB_TOKEN:-${VCPKG_NUGET_TOKEN:-}}"
    GITHUB_USER="${GITHUB_USER:-${VCPKG_NUGET_USER:-}}"

    if [[ -z "$GITHUB_TOKEN" || -z "$GITHUB_USER" ]]; then
      fail "trusted-ci mode requires GITHUB_TOKEN and GITHUB_USER." "In the workflow step, pass:\n  GITHUB_TOKEN: \${{ secrets.GH_TOKEN_DEV }}\n  GITHUB_USER: \${{ github.repository_owner }}\nFor fork PRs, use '--mode forked-pr-ci' instead."
    fi
  else
    if ! gh auth status -h github.com >/dev/null 2>&1; then
      fail "GitHub CLI is not authenticated." "Authenticate and request package-read scope:\n  gh auth login -h github.com\n  gh auth refresh -h github.com -s read:packages"
    fi

    GH_STATUS="$(gh auth status -h github.com 2>&1 || true)"
    if [[ "$GH_STATUS" != *"read:packages"* ]]; then
      fail "GitHub CLI token is missing the 'read:packages' scope." "Refresh the token scope, then rerun this script:\n  gh auth refresh -h github.com -s read:packages\n  gh auth status -h github.com"
    fi

    GITHUB_TOKEN="${GITHUB_TOKEN:-$(gh auth token)}"
    GITHUB_USER="${GITHUB_USER:-$(gh api user --jq .login)}"

    if [[ -z "$GITHUB_TOKEN" || -z "$GITHUB_USER" ]]; then
      fail "Could not resolve GitHub token or username." "Set GITHUB_TOKEN and GITHUB_USER explicitly, or fix GitHub CLI authentication with 'gh auth login'."
    fi
  fi

  NUGET_EXE="$("$ROOT_DIR/vcpkg/vcpkg" fetch nuget | tail -n 1)"
  if [[ ! -f "$NUGET_EXE" ]]; then
    fail "vcpkg did not return a usable nuget.exe path." "Run '$ROOT_DIR/vcpkg/vcpkg fetch nuget' and fix any reported vcpkg download errors."
  fi

  info "Configuring GitHub Packages NuGet source"
  mono "$NUGET_EXE" sources remove -Name "github" >/dev/null 2>&1 || true
  # NuGet on Linux under Mono needs this flag to persist the feed credential.
  mono "$NUGET_EXE" sources add \
    -Name "github" \
    -Source "$VCPKG_NUGET_FEED" \
    -UserName "$GITHUB_USER" \
    -Password "$GITHUB_TOKEN" \
    -StorePasswordInClearText >/dev/null
  mono "$NUGET_EXE" setapikey "$GITHUB_TOKEN" -Source "$VCPKG_NUGET_FEED" >/dev/null

  if [[ "$BUILD_MODE" == "developer" ]]; then
    export VCPKG_BINARY_SOURCES="clear;nuget,$VCPKG_NUGET_FEED,read"
  else
    export VCPKG_BINARY_SOURCES="clear;nuget,$VCPKG_NUGET_FEED,readwrite"
  fi
fi

if [[ "$BUILD_MODE" == "developer" ]]; then
  if ! write_developer_user_presets && [[ "$CMAKE_PRESET_EXPLICIT" -eq 0 ]]; then
    CMAKE_PRESET="vcpkg-github-release"
    info "Using committed preset '$CMAKE_PRESET' for this run"
  fi
fi

if [[ "$BUILD_MODE" == "developer" ]]; then
  case "$CMAKE_PRESET" in
    dev-debug|vcpkg-github-debug-release-deps)
      EFFECTIVE_BUILD_DIR="$BUILD_DIR/debug-release-deps"
      ;;
    *)
      EFFECTIVE_BUILD_DIR="$BUILD_DIR/release"
      ;;
  esac
else
  EFFECTIVE_BUILD_DIR="$BUILD_DIR"
fi

export CCACHE_DIR="${CCACHE_DIR:-$ROOT_DIR/.ccache}"
export CCACHE_MAXSIZE="${CCACHE_MAXSIZE:-10G}"

CMAKE_CONFIGURE_ARGS=(
  --preset "$CMAKE_PRESET"
  -B "$EFFECTIVE_BUILD_DIR"
)

if [[ -n "${SYSIO_PLATFORM_HAS_EXTRAS_CMAKE:-}" ]]; then
  CMAKE_CONFIGURE_ARGS+=(-C /extras.cmake)
fi

if [[ -n "${CC:-}" ]]; then
  CMAKE_CONFIGURE_ARGS+=(-DCMAKE_C_COMPILER="$CC")
fi

if [[ -n "${CXX:-}" ]]; then
  CMAKE_CONFIGURE_ARGS+=(-DCMAKE_CXX_COMPILER="$CXX")
fi

if [[ -n "${CMAKE_MAKE_PROGRAM:-}" ]]; then
  CMAKE_CONFIGURE_ARGS+=(-DCMAKE_MAKE_PROGRAM="$CMAKE_MAKE_PROGRAM")
fi

if [[ -n "${CMAKE_PREFIX_PATH:-}" ]]; then
  CMAKE_CONFIGURE_ARGS+=(-DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH")
fi

CONFIGURE_LOG="$EFFECTIVE_BUILD_DIR/cmake-configure.log"
mkdir -p "$EFFECTIVE_BUILD_DIR"

if [[ "$BUILD_MODE" == "developer" ]]; then
  info "Build directory prefix: $BUILD_DIR"
fi
info "Build directory: $EFFECTIVE_BUILD_DIR"
info "CMake preset: $CMAKE_PRESET"
info "Build mode: $BUILD_MODE"
info "vcpkg binary sources: $VCPKG_BINARY_SOURCES"

info "Configuring CMake"
set +e
cmake "${CMAKE_CONFIGURE_ARGS[@]}" 2>&1 | tee "$CONFIGURE_LOG"
configure_status=${PIPESTATUS[0]}
set -e

if [[ "$configure_status" -ne 0 ]]; then
  fail "CMake configure failed." "Review $CONFIGURE_LOG. Common fixes:\n  sudo apt-get install -y mono-complete ninja-build cmake\n  gh auth refresh -h github.com -s read:packages\n  rm -rf '$BUILD_DIR' and rerun this script after changing compilers."
fi

if grep -Eiq "Restored[[:space:]]+0([^0-9]|$).*package(s|\\(s\\))?.*from[[:space:]]+nuget" "$CONFIGURE_LOG"; then
  info "Warning: vcpkg reported zero NuGet restores. This can mean the ABI does not match CI, or that the packages were already installed in '$BUILD_DIR'."
elif grep -Eiq "Restored[[:space:]]+[1-9][0-9]*([^0-9]|$).*package(s|\\(s\\))?.*from[[:space:]]+nuget" "$CONFIGURE_LOG"; then
  info "Confirmed vcpkg restored packages from the GitHub NuGet cache"
else
  info "No NuGet restore line was printed. This usually means vcpkg packages were already installed in '$BUILD_DIR'."
fi

info "Building"
cmake --build "$EFFECTIVE_BUILD_DIR" -- -j "$JOBS"

if [[ "$RUN_TESTS" -eq 1 ]]; then
  info "Running tests"
  ctest --test-dir "$EFFECTIVE_BUILD_DIR" -j "$JOBS" --output-on-failure \
    -LE "(nonparallelizable_tests|long_running_tests|wasm_spec_tests)"
fi

info "Done"
