import { execFileSync } from "node:child_process"
import Fs from "node:fs"
import Path from "node:path"
import { log } from "../util/logger.js"
import { renderTemplate } from "../util/templates.js"
import { resolvePluginBin, findProtoRoot } from "./runProtoc.js"
import { Target, TemplatePath, TemplateFile } from "../constants.js"

export interface GenerateTypescriptOptions {
  target: Target
  protoFiles: string[]
  protoDir: string
  tmpDir: string
  outputDir: string
}

/**
 * Strip `.pb` from a filename.
 * e.g. "Types.pb.ts" → "Types.ts"
 */
function stripPb(filename: string): string {
  return filename.replace(/\.pb\.(\w+)$/, ".$1")
}

function walkDir(dir: string): string[] {
  if (!Fs.existsSync(dir)) return []
  return Fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const fullPath = Path.join(dir, entry.name)
    return entry.isDirectory() ? walkDir(fullPath) : [fullPath]
  })
}

/**
 * Generate TypeScript types from proto files.
 *
 * 1. Runs protoc with protoc-gen-ts (@protobuf-ts/plugin)
 * 2. Copies .ts files to outputDir, stripping .pb from names
 * 3. Generates barrel index.ts
 * 4. Writes tsconfig files from typescript templates
 */
export async function generateTypescript(
  opts: GenerateTypescriptOptions
): Promise<void> {
  const { protoFiles, protoDir, tmpDir, outputDir } = opts

  // ── Step 1: Run protoc with protoc-gen-ts ──────────────────────────────
  const tsOutputDir = Path.join(tmpDir, "ts"),
    tsGenDir = Path.join(tsOutputDir, "generated")
  Fs.mkdirSync(tsGenDir, { recursive: true })

  const pluginBin = resolvePluginBin("protoc-gen-ts", "@protobuf-ts/plugin")
  log.debug("Resolved protoc-gen-ts binary: %s", pluginBin)

  const protoRoot = findProtoRoot(protoDir),
    relativeProtos = protoFiles.map(p => Path.relative(protoRoot, p))

  const args = [
    `--plugin=protoc-gen-ts=${pluginBin}`,
    `--proto_path=${protoRoot}`,
    `--ts_out=${tsGenDir}`,
    ...relativeProtos
  ]

  log.info("Running protoc for TypeScript: npx protoc %s", args.join(" "))

  try {
    execFileSync("npx", ["protoc", ...args], {
      stdio: ["pipe", "pipe", "inherit"]
    })
  } catch (err: any) {
    throw new Error(
      `protoc (TypeScript) failed (exit ${err.status}): ${err.stderr?.toString() ?? err.message}`
    )
  }

  // ── Step 2: Copy .ts files to outputDir, stripping .pb ─────────────────

  const tsFiles = walkDir(tsGenDir).filter(f => f.endsWith(".ts"))
  log.info("protoc-gen-ts generated %d file(s)", tsFiles.length)

  const tsSrcPath = Path.join(outputDir, "src")
  Fs.mkdirSync(tsSrcPath, { recursive: true })

  const tsModules = tsFiles.map(file => {
    const rel = Path.relative(tsGenDir, file),
      cleaned = Path.join(Path.dirname(rel), stripPb(Path.basename(rel)))

    // Fail fast if TS output would collide with contracts/
    const firstSegment = cleaned.split(Path.sep)[0]
    if (firstSegment === "contracts") {
      throw new Error(
        `TypeScript generation would place files under "contracts/" ` +
          `which collides with the Solidity contracts directory. ` +
          `Proto path "${rel}" maps to "${cleaned}".`
      )
    }

    const dest = Path.join(tsSrcPath, cleaned)
    Fs.mkdirSync(Path.dirname(dest), { recursive: true })
    Fs.copyFileSync(file, dest)
    return cleaned
  })

  // ── Step 3: Generate barrel index.ts ───────────────────────────────────

  const barrelLines = [
    "// Auto-generated by protobuf-bundler — do not edit",
    "",
    ...tsModules.sort().map(mod => {
      let importPath =
        "./" + mod.replace(/\.ts$/, ".js").split(Path.sep).join("/")
      if (!importPath.endsWith(".js")) importPath += ".js"
      return `export * from "${importPath}";`
    }),
    ""
  ]

  Fs.writeFileSync(Path.join(tsSrcPath, "index.ts"), barrelLines.join("\n"))

  // ── Step 4: Write tsconfig files from typescript templates ─────────────

  const tsconfigContent = renderTemplate(
      TemplatePath[opts.target][TemplateFile.TSConfig],
      {}
    ),
    tsconfigCJSContent = renderTemplate(
      TemplatePath[opts.target][TemplateFile.TSConfigCJS],
      {}
    ),
    tsconfigESMContent = renderTemplate(
      TemplatePath[opts.target][TemplateFile.TSConfigESM],
      {}
    )
  Fs.writeFileSync(Path.join(outputDir, "tsconfig.json"), tsconfigContent)
  Fs.writeFileSync(
    Path.join(outputDir, "tsconfig.cjs.json"),
    tsconfigCJSContent
  )
  Fs.writeFileSync(
    Path.join(outputDir, "tsconfig.esm.json"),
    tsconfigESMContent
  )

  log.info("TypeScript generation complete: %d module(s)", tsModules.length)
}
