file(TOUCH ${CMAKE_BINARY_DIR}/.wire-build-root)

if (UNIX)
    if (APPLE)
        set(whole_archive_flag "-force_load")
        set(no_whole_archive_flag "")
        set(build_id_flag "")
    else ()
        set(whole_archive_flag "--whole-archive")
        set(no_whole_archive_flag "--no-whole-archive")
        set(build_id_flag "--build-id")
    endif ()
else ()
    set(whole_archive_flag "--whole-archive")
    set(no_whole_archive_flag "--no-whole-archive")
    set(build_id_flag "")
endif ()