file(TOUCH ${CMAKE_BINARY_DIR}/.wire-build-root)

if (UNIX)
    if (APPLE)
        set(whole_archive_flag "-force_load")
        set(no_whole_archive_flag "")
        set(build_id_flag "")
    else ()
        set(whole_archive_flag "--whole-archive")
        set(no_whole_archive_flag "--no-whole-archive")
        set(build_id_flag "--build-id")
    endif ()
else ()
    set(whole_archive_flag "--whole-archive")
    set(no_whole_archive_flag "--no-whole-archive")
    set(build_id_flag "")
endif ()

# Remove any linuxbrew paths from PATH to avoid conflicts with system libraries/compilers
string(REPLACE ":" ";" _path_list "$ENV{PATH}")
set(_clean_path "")
foreach(_p IN LISTS _path_list)
    if(NOT _p MATCHES "linuxbrew")
        list(APPEND _clean_path "${_p}")
    endif()
endforeach()
string(REPLACE ";" ":" _clean_path_str "${_clean_path}")
set(ENV{PATH} "${_clean_path_str}")
