name: Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'libraries/**'
      - 'programs/**'
      - 'plugins/**'
      - 'unittests/**'
      - 'tests/**'

jobs:
  build-and-test:
    runs-on: [self-hosted, 'main', 'enf-x86-hightier']
    timeout-minutes: 60

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug GitHub context
        run: |
          echo "GITHUB_REF:        $GITHUB_REF"
          echo "GITHUB_HEAD_REF:   $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF:   $GITHUB_BASE_REF"
          echo "PR clone URL:      ${{ github.event.pull_request.head.repo.clone_url }}"
          echo "github.head_ref:   ${{ github.head_ref }}"
          echo "Contents of \$GITHUB_EVENT_PATH:"
          cat "$GITHUB_EVENT_PATH"

      - name: Build Docker image
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          REPO="${{ github.event.pull_request.head.repo.clone_url || format('https://github.com/{0}.git', github.repository) }}"
          echo "Using BRANCH=$BRANCH"
          echo "Using REPO=$REPO"
      
          sudo  ./scripts/docker-build.sh \
            --target=app-build-repo \
            --tag=wire-sysio-build \
            --sysio-branch=$BRANCH

      - name: Run CTest suite
        run: |
          sudo docker run --rm wire-sysio-build \
            bash -c 'cd /wire/wire-sysio/build/Release && ctest -j $(nproc) -LE _tests --output-on-failure'
