name: Build & Test

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: [self-hosted, '${{ github.repository }}']
    timeout-minutes: 60

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug GitHub context
        run: |
          echo "GITHUB_REF:        $GITHUB_REF"
          echo "GITHUB_HEAD_REF:   $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF:   $GITHUB_BASE_REF"
          echo "PR clone URL:      ${{ github.event.pull_request.head.repo.clone_url }}"
          echo "github.head_ref:   ${{ github.head_ref }}"
          echo "Contents of \$GITHUB_EVENT_PATH:"
          cat "$GITHUB_EVENT_PATH"

      - name: Build Docker image
        run: |
          sudo docker build --no-cache --pull \
            --build-arg BRANCH=${{ github.head_ref }} \
            --build-arg REPO=${{ github.event.pull_request.head.repo.clone_url }} \
            -t wire-sysio-build .

      - name: Run CTest suite
        run: |
          sudo docker run --rm wire-sysio-build \
            bash -c "cd /wire/wire-sysio/build && ctest -j $(nproc) -LE _tests"